production:
  adapter: postgresql
  database: development
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: development
  host: localhost

test:
  adapter: postgresql
  database: pg_test
  encoding: unicode
  host: localhost
